---
swagger: "2.0"
info:
  description: "This is a simple service that will recieve a string in the query param\
    \ and process the string to deliver the desired result. \n Note: character limitation\
    \ is 50"
  version: "1.0.0"
  title: "String Prcessing Center"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "rashray@iu.edu"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:8080"
basePath: "/v2"
tags:
- name: "Strings"
  description: "String queries are processed here"
paths:
  /addString:
    get:
      tags:
      - "Strings"
      summary: "Add the string"
      description: "This method will add the string from the query param to the data\
        \ collection"
      operationId: "add_str"
      consumes:
      - "string"
      produces:
      - "application/json"
      parameters:
      - name: "str"
        in: "query"
        description: "The string to be processed"
        required: true
        type: "string"
      responses:
        200:
          description: "Successfully processed the string"
        401:
          description: "String length geater than limit"
        405:
          description: "Please enter a valid string"
      x-swagger-router-controller: "swagger_server.controllers.strings_controller"
  /fetchString:
    get:
      tags:
      - "Strings"
      summary: "Get the string by id"
      description: "This method fetch the string by id"
      operationId: "fetch_str"
      consumes:
      - "string"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "query"
        description: "The string to be processed"
        required: true
        type: "string"
      responses:
        200:
          description: "Successfully processed the string"
        401:
          description: "String length geater than limit"
        405:
          description: "Please enter a valid string"
      x-swagger-router-controller: "swagger_server.controllers.strings_controller"
  /parseString:
    get:
      tags:
      - "Strings"
      summary: "List 1. all the unique characters; 2. numeric digits count"
      description: "Get all the unique characters in the string listed in an array\
        \ and the total number of numeric digits in the string"
      operationId: "parse_str"
      consumes:
      - "string"
      produces:
      - "application/json"
      parameters:
      - name: "str"
        in: "query"
        description: "The string to be processed"
        required: true
        type: "string"
      responses:
        200:
          description: "Successfully processed the string"
        401:
          description: "String length geater than limit"
        405:
          description: "Please enter a valid string"
      x-swagger-router-controller: "swagger_server.controllers.strings_controller"
  /getMatchData:
    get:
      tags:
      - "Strings"
      summary: "String Match"
      description: "Find the matching data of two strings"
      operationId: "match_str"
      consumes:
      - "string"
      produces:
      - "application/json"
      parameters:
      - name: "subStr"
        in: "query"
        description: "The string to be matched"
        required: true
        type: "string"
      - name: "str"
        in: "query"
        description: "The string to be processed"
        required: true
        type: "string"
      responses:
        200:
          description: "Successfully processed the string"
        401:
          description: "String length geater than limit"
        405:
          description: "Please enter a valid string"
      x-swagger-router-controller: "swagger_server.controllers.strings_controller"
  /replaceString:
    get:
      tags:
      - "Strings"
      summary: "Replace one old str with the new one"
      description: "Replace the old str with the new one with in a new string."
      operationId: "replace_str"
      consumes:
      - "string"
      produces:
      - "application/json"
      parameters:
      - name: "oldStr"
        in: "query"
        description: "Sub string to be replaced"
        required: true
        type: "string"
      - name: "newStr"
        in: "query"
        description: "Sub string replacing the old value"
        required: true
        type: "string"
      - name: "str"
        in: "query"
        description: "The string to be processed"
        required: true
        type: "string"
      responses:
        200:
          description: "Successfully processed the string"
        401:
          description: "String length geater than limit"
        405:
          description: "Atleast one substr is bigger than the parent"
      x-swagger-router-controller: "swagger_server.controllers.strings_controller"
definitions: {}
