# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class OUTPUT(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, finalstring=None):  # noqa: E501
        """OUTPUT - a model defined in Swagger

        :param finalstring: The finalstring of this OUTPUT.  # noqa: E501
        :type finalstring: str
        """
        self.swagger_types = {
            'finalstring': str
        }

        self.attribute_map = {
            'finalstring': 'finalstring'
        }

        self._finalstring = finalstring

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The OUTPUT of this OUTPUT.  # noqa: E501
        :rtype: OUTPUT
        """
        return util.deserialize_model(dikt, cls)

    @property
    def finalstring(self):
        """Gets the finalstring of this OUTPUT.


        :return: The finalstring of this OUTPUT.
        :rtype: str
        """
        return self._finalstring

    @finalstring.setter
    def finalstring(self, finalstring):
        """Sets the finalstring of this OUTPUT.


        :param finalstring: The finalstring of this OUTPUT.
        :type finalstring: str
        """
        if finalstring is None:
            raise ValueError("Invalid value for `finalstring`, must not be `None`")  # noqa: E501

        self._finalstring = finalstring
